### ISSUE TITLE
ubuntu on windows 10

### ISSUE THREAD

**Issue by MichaelAlex86** [vodolaz095/gossha#1]
Работает ли gossha в ubuntu on windows 10 ?
После всей установки и запуска, выдает это:
   ____      ____ ____  _   _
 /  ___| ___/ ___/ ___|| | | | __ _
|  |  _ / _ \___ \___ \| |_| |/ _` |
|  |_| | (_) |__) |__) |  _  | (_| |
 \____|\___/____/____/|_| |_|\__,_|

Cross-platform ssh-server based chat program.
Build: 2.0.0.cd1a7e0.Linux-x86_64
Homepage: https://github.com/vodolaz095/gossha
Error reporting: https://github.com/vodolaz095/gossha/issues
API documentation: https://godoc.com/github.com/vodolaz095/gossha

Try `gossha help` for help...

GoSSHa is listening on 0.0.0.0:27016 port!
GoSSHa is listening on 127.0.0.1:27014 port!
---------------------------------------------------------------
А дальше команды не воспринимает....

**Comment by vodolaz095** [comment]
Про ` ubuntu on windows 10` - не знаю, крайний раз я использовал Windows 98 в 2002 году.
Лично я обычно гоняю Fedora/Centos/Archlinux даже на домашних компьютерах
Про `А дальше команды не воспринимает....`

во первых, попробуйте создать пользователя `root` с паролем `test321`

`$ gossha root root test 321`

(то есть сначала создать пользователя, а потом запускать как сервер)

И после запуска сервера попробуйте подсоединиться по протоколу ssh (на сколько я знаю, в винде есть клиент putty)
на  27016 или 27014 порты как пользователь `root` с паролем `test 321`.

если получилось авторизоваться, Вы можете создать других пользователей, а потом уже попробывать авторизоваться этими пользователями.


По умолчанию используйеться sqlite база данных в `~/.config/gossha/`

**Comment by MichaelAlex86** [comment]
Спасибо, запустить удалось.
 Ubuntu on windows 10, штука загадочная и урезанная, пришлось помучиться.

Через виндовые клиенты, putty и kitty подключается, а так же через стандартный openSSH-client в Linux системах. Через JuiceSSH android не хочет.

**Comment by vodolaz095** [comment]
как я понял, всё работает и сообщение об ошибке можно закрыть?
